--SEPUTAR category
SELECT *
FROM CATEGORY;

SELECT *
FROM PRODUCT_CATEGORY;

INSERT INTO CATEGORY(ID, NAME)
VALUES(NULL, 'Makanan Pedas');

DELETE FROM category where id=26;

-- PL SQL PROCEDURE/FUNCTION DECLARATION
CREATE OR REPLACE FUNCTION CREATE_CATEGORY(L_NAME IN STRING) RETURN INTEGER
AS
L_FLAG INTEGER;
BEGIN
    SELECT ID INTO L_FLAG
    FROM CATEGORY
    WHERE LOWER(NAME) = LOWER(L_NAME);
    
    RETURN 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            INSERT INTO CATEGORY(ID, NAME)
            VALUES(NULL, L_NAME);
            RETURN 0;
END;
/

CREATE OR REPLACE PACKAGE CATEGORY_PKG IS
    TYPE ARRAY_OF_INTEGER IS TABLE OF INTEGER INDEX BY BINARY_INTEGER;
    PROCEDURE ADD_PRODUCT_CATEGORY(L_PRODUCT_ID IN INTEGER, L_CATEGORY_ID IN ARRAY_OF_INTEGER);
END;
/

CREATE OR REPLACE PACKAGE BODY CATEGORY_PKG IS
    PROCEDURE ADD_PRODUCT_CATEGORY(L_PRODUCT_ID IN INTEGER, L_CATEGORY_ID IN ARRAY_OF_INTEGER) 
    IS
    BEGIN
        FORALL X IN INDICES OF L_CATEGORY_ID
            INSERT INTO PRODUCT_CATEGORY(PRODUCT_ID, CATEGORY_ID)
            VALUES(L_PRODUCT_ID, L_CATEGORY_ID(X));
    END;
END;
/