-- DATA MANIPULATION LANGUAGE
SET SERVEROUTPUT ON;
--SEPUTAR MERCHANT
SELECT *
FROM MERCHANT;

INSERT INTO MERCHANT (id, name, username, password)
VALUES(NULL, 'Seblack Gila', 'seblak', 'seblak');

CREATE OR REPLACE FUNCTION AUTHENTICATE_MERCHANT(L_USERNAME IN STRING, L_PASSWORD IN STRING, L_ID OUT INTEGER) RETURN INTEGER
AS
L_MERCHANT MERCHANT%ROWTYPE;
BEGIN
    SELECT * INTO L_MERCHANT
    FROM MERCHANT
    WHERE USERNAME = L_USERNAME AND PASSWORD = L_PASSWORD;

    L_ID := L_MERCHANT.ID;

    RETURN 0;
    EXCEPTION 
        WHEN NO_DATA_FOUND THEN
            RETURN 1;

END;

--SEPUTAR category
SELECT *
FROM CATEGORY;

INSERT INTO CATEGORY(ID, NAME)
VALUES(NULL, 'Susu');

DELETE FROM category where id=26;

--SEPUTAR PRODUCTS
SELECT *
FROM PRODUCT;

INSERT INTO PRODUCT (ID, DESCRIPTION, TITLE, PRICE, IMAGE_URL, STOCK, CATEGORY_ID, MERCHANT_ID)
VALUES(NULL, 'Seblak super pedes', 'Seblak Gila', 15000, 'google.com', 10, 1, 21);

UPDATE PRODUCT SET
    STOCK = 100;

CREATE OR REPLACE FUNCTION ADD_NEW_PRODUCT(L_TITLE IN STRING, L_DESCRIPTION IN STRING, L_PRICE IN INTEGER, L_STOCK IN INTEGER, L_IMAGE_URL IN CLOB, L_CATEGORY_ID IN INTEGER, L_MERCHANT_ID) RETURN INTEGER
AS
BEGIN
    INSERT INTO PRODUCT (ID, )
    
END;


    

    


