CREATE OR REPLACE VIEW JOINED_CART_PRODUCT AS
    SELECT PRODUCT_ID, CART_ID, TITLE, DESCRIPTION, IMAGE_URL, PRICE, STOCK, MERCHANT_ID
    FROM CART_ITEM
    INNER JOIN PRODUCT ON PRODUCT_ID = PRODUCT.ID;
    
SELECT * FROM JOINED_CART_PRODUCT;

CREATE OR REPLACE VIEW AVAILABLE_PRODUCT AS
    SELECT PRODUCT.ID, TITLE, DESCRIPTION, IMAGE_URL, PRICE, STOCK, MERCHANT_ID
    FROM PRODUCT
    INNER JOIN MERCHANT ON MERCHANT_ID = MERCHANT.ID
    WHERE MERCHANT.STATUS = 1 AND STOCK > 0;