CREATE OR REPLACE VIEW JOINED_CART_PRODUCT AS
    SELECT PRODUCT_ID, CART_ID, TITLE, DESCRIPTION, IMAGE_URL, PRICE, STOCK, MERCHANT_ID
    FROM CART_ITEM
    INNER JOIN PRODUCT ON PRODUCT_ID = PRODUCT.ID;
    
SELECT * FROM JOINED_CART_PRODUCT;