CREATE OR REPLACE FUNCTION AUTHENTICATE_ADMIN(L_USERNAME IN STRING, L_PASSWORD IN STRING) RETURN INTEGER
AS
    L_ADMIN ADMIN%ROWTYPE;
BEGIN
    SELECT * INTO L_ADMIN
    FROM ADMIN A
    WHERE (A.USERNAME = L_USERNAME AND A.PASSWORD = L_PASSWORD) AND (A.IS_LOGIN = 0);

    UPDATE ADMIN SET
        IS_LOGIN = 1
    WHERE USERNAME = L_USERNAME;

    RETURN 0;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 1;
END;
/

CREATE OR REPLACE PROCEDURE LOGOUT_ADMIN(L_USERNAME IN STRING) 
IS
BEGIN
    UPDATE ADMIN SET
        IS_LOGIN = 0
    WHERE ADMIN.USERNAME = L_USERNAME;
END;
/