-- DATA MANIPULATION LANGUAGE
SET SERVEROUTPUT ON;
-- ORDERS
SELECT * FROM ORDERS;

SELECT * FROM ORDERS_ITEM;

-- INVOICE
SELECT * FROM INVOICE;

-- PAYMENT
SELECT * FROM PAYMENT;

INSERT INTO PAYMENT(ID, METHOD, ACC_NUMBER, status)
VALUES (NULL, 'GOPAY', '082317900923', 1);

--
-- PL SQL PROCEDURE FUNCTION DECLARATION
--
CREATE OR REPLACE PROCEDURE READ_ALL_INVOICE
IS
    L_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN L_CURSOR FOR
        SELECT *
        FROM INVOICE;
    
    DBMS_SQL.RETURN_RESULT(L_CURSOR);
END;
/
    
CREATE OR REPLACE PROCEDURE READ_INVOICE_BYCUSTOMER(L_CUSTOMER_ID IN INTEGER)
IS
    L_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN L_CURSOR FOR
        SELECT *
        FROM INVOICE
        WHERE CUSTOMER_ID = L_CUSTOMER_ID;
    
    DBMS_SQL.RETURN_RESULT(L_CURSOR);
END;
/


