-- DATA MANIPULATION LANGUAGE
SET SERVEROUTPUT ON;
-- ORDERS
SELECT * FROM ORDERS;

SELECT * FROM ORDERS_ITEM;

-- INVOICE
SELECT * FROM INVOICE;

-- PAYMENT
SELECT * FROM PAYMENT;

INSERT INTO PAYMENT(ID, METHOD, ACC_NUMBER, status)
VALUES (NULL, 'GOPAY', '082317900923', 1);

--
-- PL SQL PROCEDURE FUNCTION DECLARATION
--
CREATE OR REPLACE PROCEDURE READ_ORDERS_DETAIL(L_ORDERS_ID IN INTEGER)
IS
    L_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN L_CURSOR FOR
        SELECT ORDERS_ID, PRODUCT_ID, TITLE, QUANTITY, NOTE
        FROM ORDERS_ITEM
        INNER JOIN PRODUCT ON PRODUCT_ID = PRODUCT.ID
        WHERE ORDERS_ID = L_ORDERS_ID;
    
    DBMS_SQL.RETURN_RESULT(L_CURSOR);
END;
/

CREATE OR REPLACE PROCEDURE READ_ORDERS_BYCUSTOMER(L_CUSTOMER_ID IN INTEGER)
IS
    L_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN L_CURSOR FOR
        SELECT *
        FROM ORDERS
        WHERE CUSTOMER_ID = L_CUSTOMER_ID;
    
    DBMS_SQL.RETURN_RESULT(L_CURSOR);
END;
/

CREATE OR REPLACE PROCEDURE READ_ORDERS_BYMERCHANT(L_MERCHANT_ID IN INTEGER)
IS
    L_CURSOR SYS_REFCURSOR;
BEGIN
    OPEN L_CURSOR FOR
        SELECT *
        FROM ORDERS
        WHERE MERCHANT_ID = L_MERCHANT_ID;
    
    DBMS_SQL.RETURN_RESULT(L_CURSOR);
END;
/





    

    


